services:
  postgres:
    container_name: pgdev
    image: docker.io/postgres
    environment:
      POSTGRES_USER: sirat
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  mongodb:
    container_name: mogodev
    image: docker.io/mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopw
    ports:
      - 27017:27017
    volumes:
      - mongodata:/var/lib/mongodb/data
  rabbitmq:
    container_name: rabbitmqdev
    image: docker.io/rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
volumes:
  pgdata:
  mongodata:
