services:
  postgres:
    image: docker.io/postgres
    environment:
      POSTGRES_USER: sirat
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
